build linux:
  stage: build
  image: harbor.feysh.local/corax/gradle:v1
  tags:
    - "k8s-runner"
  script:
    - gradle build -x test

deploy:
  image: harbor.feysh.local/corax/gradle:v1
  tags:
    - "k8s-runner"
  script:
    - gradle publish
  when: manual
