build linux:
  stage: build
  image:
    name: harbor.corax.local/corax/builder/jdk17:v3
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  tags:
    - "k8s-runner"
  script:
    - ./gradlew build -x test "-PsemVer=$CI_COMMIT_REF_NAME"

deploy:
  image:
    name: harbor.corax.local/corax/builder/jdk17:v3
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  tags:
    - "k8s-runner"
  script:
    - ./gradlew publish "-PsemVer=${CI_COMMIT_REF_NAME}-CORAX-FORK"
  when: manual
